spring:
  mail:
    host: smtp.163.com
    username: w954485947@163.com
    password: ATFTNZYUQBRFTJAF
  rabbitmq:
    addresses: localhost
    username: admin
    password: 123123
    virtual-host: /test
  security:
    filter:
      order: -100
    jwt:
      key: asdfg
      expire: 7
  datasource:
    url: jdbc:mysql://localhost:3306/login_test_jwt
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver
